import {adminUser,database,json,readContent,sameOrigin,validate} from '../../../lib/cms';
export const dynamic='force-dynamic';
export async function GET(){if(!await adminUser())return json({error:'Bạn chưa có quyền quản trị.'},403);try {const content=await readContent();const leads=await database().prepare('SELECT * FROM leads ORDER BY created_at DESC LIMIT 500').all();const audit=await database().prepare('SELECT action,target,created_at FROM audit ORDER BY created_at DESC LIMIT 12').all();return json({...content,leads:leads.results,audit:audit.results})}catch{return json({error:'Không tải được dữ liệu. Vui lòng thử lại.'},503)}}
export async function POST(request:Request){const user=await adminUser();if(!user)return json({error:'Bạn chưa có quyền quản trị.'},403);if(!sameOrigin(request))return json({error:'Yêu cầu không hợp lệ.'},403);try{const raw=await request.text();if(raw.length>250000)return json({error:'Nội dung quá dài.'},413);const b=JSON.parse(raw);const db=database(),now=new Date().toISOString();
 if(b.kind==='lead'){if(!['new','contacted','scheduled','closed'].includes(b.status)||!['browsing','potential','ready'].includes(b.customerType)||typeof b.note!=='string'||b.note.length>3000)return json({error:'Dữ liệu không hợp lệ.'},400);const result=await db.batch([db.prepare('UPDATE leads SET status=?,customer_type=?,note=?,updated_at=? WHERE id=?').bind(b.status,b.customerType,b.note,now,b.id),db.prepare('INSERT INTO audit (id,actor,action,target,created_at) VALUES (?,?,?,?,?)').bind(crypto.randomUUID(),user.userId,'Cập nhật khách hàng',b.id,now)]);if(!result[0].meta.changes)return json({error:'Không tìm thấy khách hàng.'},404);return json({ok:true})}
 if(!validate(b.key,b.value)||!Number.isInteger(b.revision)||b.revision<0)return json({error:'Kiểm tra lại nội dung, đường dẫn ảnh và giá xe.'},400);
 const result=await db.prepare('INSERT INTO content (key,value,revision,updated_at,updated_by) VALUES (?,?,1,?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value,revision=content.revision+1,updated_at=excluded.updated_at,updated_by=excluded.updated_by WHERE content.revision=?').bind(b.key,JSON.stringify(b.value),now,user.userId,b.revision).run();
 if(!result.meta.changes)return json({error:'Nội dung đã được sửa ở cửa sổ khác. Tải lại trước khi lưu.'},409);
 await db.prepare('INSERT INTO audit (id,actor,action,target,created_at) VALUES (?,?,?,?,?)').bind(crypto.randomUUID(),user.userId,'Lưu nội dung',b.key,now).run();return json({ok:true,revision:b.revision+1});
 }catch{return json({error:'Không lưu được dữ liệu. Vui lòng thử lại.'},503)}}
